### ISSUE TITLE
RECORD AND SCREENSHOT

### ISSUE THREAD

**Issue by Secrets123212** [seungwoochoe/bypassing-LockDown-Browser-demonstration#1]
How to take screen shot or record in lock down?

**Comment by seungwoochoe** [comment]
You can start screen recording before opening LockDown Browser.

**Comment by Secrets123212** [comment]
Yes, but its showing Black Screen

**Comment by seungwoochoe** [comment]
I don't think I can help you with that then. The built-in Screenshot.app works fine for me.

**Comment by Secrets123212** [comment]
Your using which app ?

**Comment by seungwoochoe** [comment]
> The built-in Screenshot.app works fine for me.
